### ISSUE TITLE
Couple of adjustments and suggestions

### ISSUE THREAD

**Issue by amazaheri** [microsoft/MCW-Microservices-architecture#6]
In prep and on diagram Azure Functions are under a separate RG but in steps it's being provisioned under same RG as other components (Which should be fine).

Exercise 3
Task 5 (Item 24) - Instead of copy and paste can we publish the binary (ideally using beta v2 Functions)

Task 6 - Need to mention we need to configure App Insight or switch to classic view for logs as per Guide.

Exercise 4
Task 1 (Item 8) We need to update StoreLocation and StoreName in Cloud.xml PublishProfile

**Comment by michelebusta** [comment]
The diagram will be updated with revisions re: RG setup, that must have got out of sync in last update.

Ex 3, Task 5, Item24 - we should keep these changes to process for a rewrite or follow up update where there is scope for it, also we are (I think) supposed to use released items not beta?

Task 6 - we updated to classic view due to the change in UI experience. that should work.
Ex 4 - also fixed

**Comment by DawnmarieDesJardins** [comment]
Closing as addressed in May 2019 content update.
